version: 0.0.1
form_title: A Message To Unicorn

mailer:
  host: smtp.google.com
  port: 587
  user: user
  pass: pass
  retries: 3
  send_to: secret@secret.mail
  from_email: contact@myform.com

domains:
  - example.com
  - second-example.com

logs:
  level: INFO

gpg:
  pub_key: /path/to/pub.key
